version: '3.9'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - ./data/certs:/etc/nginx/certs:ro
      - ./data/conf.d:/etc/nginx/conf.d
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-proxy

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    restart: always
    environment:
      - DEFAULT_EMAIL=yilei108@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - ./data/certs:/etc/nginx/certs:rw
      - ./data/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nginx-proxy
    depends_on:
      - nginx-proxy

networks:
  nginx-proxy:
    name: nginx-proxy
