version: '3.7'

services:
  v2ray:
    build: .
    volumes:
      - ./config.json:/etc/v2ray/config.json
    restart: always
    environment:
      - VIRTUAL_HOST=yar2v.meoop.me
      - LETSENCRYPT_HOST=yar2v.meoop.me
      - LETSENCRYPT_EMAIL=yilei108@gmail.com
    expose:
      - "9090"
    networks:
      - nginx-proxy
      - default

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
