version: '2'

services:
  nextcloud-db:
    image: mariadb
    restart: always
    volumes:
      - ./nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ZDJiZWY2
    env_file:
      - db.env

  nextcloud:
    image: nextcloud:apache
    volumes:
      - ./nextcloud:/var/www/html
    restart: always
    ports:
      - 8080:80
    environment:
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=123123
    env_file:
      - db.env
    depends_on:
      - nextcloud-db

